# Default values for progress-service.

replicaCount: 1

image:
  repository: aswin018/progress-service
  pullPolicy: Always
  tag: "dev-d2fe7b2850e2e7156d58e4c22f8a832e7f4dea25"

# Resources configured for Guaranteed QoS
resources:
  requests:
    cpu: "50m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"

service:
  type: ClusterIP
  port: 5005
  targetPort: 5005

