# Default values for progress-service.

replicaCount: 1

image:
  repository: aswin018/progress-service
  pullPolicy: Always
  tag: "dev-52284cfd40862e3a384c81608c0eb492716a07aa"

# Resources configured for Guaranteed QoS
resources:
  requests:
    cpu: "50m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"

service:
  type: ClusterIP
  port: 5005
  targetPort: 5005

