sonar.projectKey=fitforge-progress-service
sonar.projectName=fitforge-progress-service
sonar.sources=src
sonar.exclusions=**/target/**, **/build/**, **/dist/**, **/node_modules/**, **/*.test.js, .env.example, generate-test-token.js
sonar.tests=src
sonar.test.inclusions=**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
